### ISSUE TITLE
Include benefits for governments

### ISSUE THREAD

**Issue by sunitagrote** [unicef/publicgoods-toolkit#21]
Would be good to include an overview of benefits to governments - I am also missing something in particular on considerations around data ownership and management. We have heard that this in particular can be a disadvantage of proprietary solutions.

**Comment by jvasile** [comment]
I agree we might say something on this point.  Would "benefits for governments" be something for the intro section?  Or does it have a more natural place in the document?

**Comment by amye** [comment]
I see two interesting opportunities here to expand at least two areas. 
(1) Policy could use some of this, at least from the first standpoint of "benefits to governments", but I will consider where else this could be expanded.
(2) Adoptability aligns nicely with the data ownership and management question. 

@sunitagrote: is there anything else that you'd like us to consider?

**Comment by sstruble** [comment]
We included more on benefits to government in the intro section.
