### ISSUE TITLE
Make key recommendations easier to access

### ISSUE THREAD

**Issue by jvasile** [unicef/publicgoods-toolkit#27]
In the community and ecosystem section (and possibly other sections), we should make it easier to find the key recommendations.  We might pull them forward to the beginning of the doc or sections.  We might also try to find a way to typeset "Key Recommendation" boxes to make them visually distinct.

See [PR 23](https://github.com/unicef/publicgoods-toolkit/pull/23) for the genesis of this issue.

**Comment by lacabra** [comment]
Yes, completely agree on this!

**Comment by kfogel** [comment]
This has been done (for a while now, in fact).  Closing this ticket.

**Comment by kfogel** [comment]
Well, to be clear: the typesetting suggestion hasn't been done, but Key Recommendations have been pulled up to the tops of modules and made visible.
